### ISSUE TITLE
Error on opening webpage

### ISSUE THREAD

**Issue by noisyjack** [jdan/magic-hotline#1]
I'm getting an error as soon as I navigate to http://localhost:3000/ with a browser.

The initial webpage that invites you to type in a URL appears but nothing happens on entering a URL.

Console output below with username redacted.

`Server listening at http://localhost:3000
(node:34204) UnhandledPromiseRejectionWarning: Error: Request failed with status code 429
    at createError (/Users/<username removed>/github/magic-hotline/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/<username removed>/github/magic-hotline/node_modules/axios/lib/core/settle.js:17:12)
    at RedirectableRequest.handleResponse (/Users/<username removed>/github/magic-hotline/node_modules/axios/lib/adapters/http.js:278:9)
    at RedirectableRequest.emit (events.js:375:28)
    at RedirectableRequest._processResponse (/Users/<username removed>/github/magic-hotline/node_modules/follow-redirects/index.js:356:10)
    at ClientRequest.RedirectableRequest._onNativeResponse (/Users/<username removed>/github/magic-hotline/node_modules/follow-redirects/index.js:62:10)
    at Object.onceWrapper (events.js:482:26)
    at ClientRequest.emit (events.js:375:28)
    at HTTPParser.parserOnIncomingClient (_http_client.js:647:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:34204) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:34204) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:34204) UnhandledPromiseRejectionWarning: Error: Request failed with status code 429
    at createError (/Users/<username removed>/github/magic-hotline/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/<username removed>/github/magic-hotline/node_modules/axios/lib/core/settle.js:17:12)
    at RedirectableRequest.handleResponse (/Users/<username removed>/github/magic-hotline/node_modules/axios/lib/adapters/http.js:278:9)
    at RedirectableRequest.emit (events.js:375:28)
    at RedirectableRequest._processResponse (/Users/<username removed>/github/magic-hotline/node_modules/follow-redirects/index.js:356:10)
    at ClientRequest.RedirectableRequest._onNativeResponse (/Users/<username removed>/github/magic-hotline/node_modules/follow-redirects/index.js:62:10)
    at Object.onceWrapper (events.js:482:26)
    at ClientRequest.emit (events.js:375:28)
    at HTTPParser.parserOnIncomingClient (_http_client.js:647:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
(node:34204) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
[nodemon] restarting due to changes...
[nodemon] starting `node index.js`
Debugger attached.
Server listening at http://localhost:3000
(node:34380) UnhandledPromiseRejectionWarning: Error: Request failed with status code 429
    at createError (/Users/<username removed>/github/magic-hotline/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/<username removed>/github/magic-hotline/node_modules/axios/lib/core/settle.js:17:12)
    at RedirectableRequest.handleResponse (/Users/<username removed>/github/magic-hotline/node_modules/axios/lib/adapters/http.js:278:9)
    at RedirectableRequest.emit (events.js:375:28)
    at RedirectableRequest._processResponse (/Users/<username removed>/github/magic-hotline/node_modules/follow-redirects/index.js:356:10)
    at ClientRequest.RedirectableRequest._onNativeResponse (/Users/<username removed>/github/magic-hotline/node_modules/follow-redirects/index.js:62:10)
    at Object.onceWrapper (events.js:482:26)
    at ClientRequest.emit (events.js:375:28)
    at HTTPParser.parserOnIncomingClient (_http_client.js:647:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:34380) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:34380) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:34380) UnhandledPromiseRejectionWarning: Error: Request failed with status code 429
    at createError (/Users/<username removed>/github/magic-hotline/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/<username removed>/github/magic-hotline/node_modules/axios/lib/core/settle.js:17:12)
    at RedirectableRequest.handleResponse (/Users/<username removed>/github/magic-hotline/node_modules/axios/lib/adapters/http.js:278:9)
    at RedirectableRequest.emit (events.js:375:28)
    at RedirectableRequest._processResponse (/Users/<username removed>/github/magic-hotline/node_modules/follow-redirects/index.js:356:10)
    at ClientRequest.RedirectableRequest._onNativeResponse (/Users/<username removed>/github/magic-hotline/node_modules/follow-redirects/index.js:62:10)
    at Object.onceWrapper (events.js:482:26)
    at ClientRequest.emit (events.js:375:28)
    at HTTPParser.parserOnIncomingClient (_http_client.js:647:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
(node:34380) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
`

**Comment by noisyjack** [comment]
You know what, this could be because I've no credit left in my OpenAI account. Standby, will update.

**Comment by noisyjack** [comment]
Just confirmed, was related to lack of funds in OpenAI account.

Closing issue!
